services:
  mysql:
    image: mysql:8
    command: --lower_case_table_names=1 --max_connections=1000
    restart: on-failure
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql:delegated
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 1GB