spring:
  application:
    name: OAuth2 Basic Demo
  security:
    user:
      name: test
      password: test
    oauth2:
      client:
        registration:
          github:
            client-id: ${clientId}
            client-secret: ${clientSecret}