CREATE TABLE IF NOT EXISTS categories(
   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   category_name VARCHAR(1000) NOT NULL,
   description VARCHAR(1000) NOT NULL,
   image_url VARCHAR(1000) NOT NULL
);

COPY categories
FROM '/docker-entrypoint-initdb.d/categories.csv'
DELIMITER ','
CSV HEADER;


CREATE TABLE IF NOT EXISTS products(
   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   category_id INT NOT NULL REFERENCES categories(id),
   name VARCHAR(1000) NOT NULL,
   description VARCHAR(1000) NOT NULL,
   image_url VARCHAR(1000) NOT NULL,
   price MONEY NOT NULL
);

COPY products
FROM '/docker-entrypoint-initdb.d/products.csv'
DELIMITER ','
CSV HEADER;